org: '1304343402'
app: freak
stage: dev
component: nuxtjs
name: nuxtjs-NemX9BYl7
inputs:
  src:
    hook: npm run build
    dist: ./
    exclude:
      - .env
      - node_modules/**
    src: ./
  region: ap-guangzhou
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
    serviceTimeout: 60
    autoCreateDns: false
  staticConf:
    cosConf:
      replace: true
      bucket: freak-dev-1304343402
      acl:
        permissions: public-read
      sources:
        - src: .next/static
          targetDir: /_next/static
        - src: public
          targetDir: /
  isAutoCiDeploy: false
  functionConf:
    eip: false
    timeout: 3
    memorySize: 128
  layers:
    - name: '${output:${stage}:${app}:freak-layer.name}'
      version: '${output:${stage}:${app}:freak-layer.version}'
